### ISSUE TITLE
20220422, 20220423 提取确诊/无症状人数失效 from 2_extract_detail.ipynb

### ISSUE THREAD

**Issue by incoincoin** [qhduan/sh-cov#1]
你好！
感谢这份疫情指标追踪的notebook！
[20220422](https://mp.weixin.qq.com/s/LySBR0VJswl_ZI1KtWlXqw)，[20220423](https://mp.weixin.qq.com/s/YNeLEO7BZouZRfyD2TWOlA) 两日的通报文本中，由于对”确诊“和”无症状“的表达方式与之前存在差异，导致无法提取确诊/无症状人数。
具体表现在：
**20220422**

> 2022年4月22日，杨浦区新增88例本土新冠肺炎确诊病例，新增1268例本土无症状感染者，分别居住于：
> 2022年4月22日，松江区新增本土新冠肺炎确诊病例120例，新增本土无症状感染者2448例，分别居住于：

**20220423**

> 2022年4月23日，金山区新增44本土无症状感染者，其中部分病例之前已落实管控，其余居住于：

建议修改 2_extract_detail.ipynb 中 extract_block 函数的正则搜索表达式。或许有更好的表达方式。

```
def extract_block(s):
    m = block_list_re.search(s)
    if not m:
        return
    block = m.group(0)
    ret = {
        block: {}
    }
    m = re.search('(\d+)例[本土确诊|本土新冠肺炎确诊病例]', s)
    if m:
        ret[block]['quezhen'] = int(m.group(1))
    else:
        m = re.search('[本土确诊|本土新冠肺炎确诊病例](\d+)例', s)
        if m:
            ret[block]['quezhen'] = int(m.group(1))
    m = re.search('(\d+)[本土无症状|例本土无症状]', s)
    if m:
        ret[block]['wuzhengzhuang'] = int(m.group(1))
    else:
        m = re.search('[本土无症状|新增本土无症状感染者](\d+)例', s)
        if m:
            ret[block]['wuzhengzhuang'] = int(m.group(1))
    return ret
```

**Comment by qhduan** [comment]
尝试做了一些更新，没有更仔细的看，你提到的几个case都看了

**Comment by incoincoin** [comment]
问题已解决，谢谢！
